@url = http://localhost:3003

### Get all blogs
GET {{url}}/api/blogs

### Create blog
POST {{url}}/api/blogs
content-type: application/json

{
    "title": "sample blog 2",
    "author": "Leon2",
    "url": "www.leonblog2.com",
    "likes": 10
}

### Get all users
GET {{url}}/api/users

### Create user
POST {{url}}/api/users
content-type: application/json

{
    "username": "leon",
    "name": "Leon Seet",
    "password": "password"
}

### User Login
POST {{url}}/api/login
content-type: application/json

{
    "username": "leon",
    "password": "password"
}