@url = http://localhost:3003

### Get all blogs
GET {{url}}/api/blogs

### Create blog
POST {{url}}/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imxlb24iLCJpZCI6IjYzNmFmY2MzZWE1Zjk5MGNiYjJlMTc5YiIsImlhdCI6MTY2Nzk1NjYxM30.E0tQFYRFWsC-MdOt-YSkB3k6KsHDQWuj0tpe6pVWSKE

{
    "title": "sample blog 2",
    "author": "Leon",
    "url": "www.leonblog.com",
    "likes": 10
}

### Get all users
GET {{url}}/api/users

### Create user
POST {{url}}/api/users
content-type: application/json

{
    "username": "leon",
    "name": "Leon Seet",
    "password": "password"
}

### User Login
POST {{url}}/api/login
content-type: application/json

{
    "username": "leon2",
    "password": "password"
}

### Delete blog
DELETE {{url}}/api/blogs/63684bdd20358df9002782f3
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imxlb24yIiwiaWQiOiI2MzY4NGJmNzIwMzU4ZGY5MDAyNzgyZjciLCJpYXQiOjE2Njc3Nzk1ODN9.RFszyJw2jTE0MbWwM4YyX2AJOA8bBgx1cxhSaafv00M

### Update blog
PUT {{url}}/api/blogs/636d90377b19afaa26bb7b55
content-type: application/json

{
    "user": "636ef51c1fe5b184782c9efc",
    "title": "udpated title",
    "author": "updated author",
    "url": "updated url",
    "likes": 200
}
