@url = http://localhost:3003

### Get all blogs
GET {{url}}/api/blogs

### Create blog
POST {{url}}/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imxlb24yIiwiaWQiOiI2MzY3MjYwZTk1MjA3YWI2OTNkMWM4NWUiLCJpYXQiOjE2Njc3MDQzNDJ9.qxhU6jqNT3UUYUbSsrODEVWoBcUuojVyn605LDoX20A

{
    "title": "sample blog 2",
    "author": "Leon",
    "url": "www.leonblog.com",
    "likes": 10
}

### Get all users
GET {{url}}/api/users

### Create user
POST {{url}}/api/users
content-type: application/json

{
    "username": "leon2",
    "name": "Leon Seet",
    "password": "password"
}

### User Login
POST {{url}}/api/login
content-type: application/json

{
    "username": "leon2",
    "password": "password"
}

### Delete blog
DELETE {{url}}/api/blogs/6367264195207ab693d1c862
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imxlb24yIiwiaWQiOiI2MzY3MjYwZTk1MjA3YWI2OTNkMWM4NWUiLCJpYXQiOjE2Njc3MDQzNDJ9.qxhU6jqNT3UUYUbSsrODEVWoBcUuojVyn605LDoX20A


