@baseurl = http://localhost:3001

GET {{baseurl}}/api/persons

###
GET {{baseurl}}/api/persons/6355eafd7e6660075eee3dbd

###
GET {{baseurl}}/info

###
DELETE {{baseurl}}/api/persons/6359d27c2769bf468c3f321a

###
POST {{baseurl}}/api/persons
content-type: application/json

{
    "name": "Leon2",
    "number": "123-12345678911"
}

###
GET {{baseurl}}/error

###
PUT {{baseurl}}/api/persons/6358837602c2d610b09737e0
content-type: application/json

{
    "name": "Leon",
    "number": "12345"
}